POST http://localhost:8080/user/register
Content-Type: application/json

{
  "email": "uygar.aras@ug.bilkent.edu.tr",
  "password": "u"
}

###
GET http://localhost:8080/items?category=lostItem

###
GET http://localhost:8080/items/3

###
POST http://localhost:8080/items
Content-Type: application/json

{
    "type": "lostItem",
    "title": "Your Title",
    "description": "Your Description",
    "imageUrl": "Your Image URL",
    "location": null,
    "dateLost": null,
    "given": false
  }

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "uygararas3@gmail.com",
  "password": "u"
}

###
GET http://localhost:8080/user/get-email
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1eWdhcmFyYXMzQGdtYWlsLmNvbSIsImV4cCI6MTcwMjI5Njk2OCwiaWF0IjoxNzAxOTM2OTY4LCJlbWFpbCI6InV5Z2FyYXJhczNAZ21haWwuY29tIn0.sih4JyBb6rdVS_csMHKSLWYmJ1kCWQvMggK
